[project]
name = "pac-man"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "cali-pso", email = "raphael.poggi@laposte.net" }
]
requires-python = ">=3.13"
dependencies = [
    "mlx",
    "pydantic>=2.13.5",
]

[project.scripts]
pac-man = "pac_man:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
mlx = { path = "mlx-2.4-py3-none-any.whl" }
